# Generated by Django 5.2.4 on 2025-07-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='Identifier for the user (e.g., email, session ID)', max_length=255)),
                ('topic', models.CharField(help_text='The topic that was studied', max_length=255)),
                ('hours', models.DecimalField(decimal_places=2, help_text='Hours spent studying the topic', max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The exact time when the progress was recorded')),
            ],
            options={
                'verbose_name_plural': 'Study Progress Entries',
            },
        ),
    ]
